/**
 * Taxonomia anatômica equina — DOMÍNIO. Fonte única de verdade.
 * paridade: "axial" (sem lado) | "mediano" (linha média lateralizável — lado OPCIONAL)
 *         | "bilateral" (pareado — lado ESPERADO). Superseded p/ regras clínicas por s2vet-clinica.model.ts.
 */
import { z } from "zod";

export const PARTE_IDS = ["cranio", "mandibula", "regiao_cervical", "cernelha", "escapula", "art_ombro", "umero", "cotovelo", "antebraco", "carpo_ant", "metacarpo", "boleto_ant", "casco_ant", "dorso", "lombo", "gradil_costal", "garupa", "tuber_coxae", "art_coxofemoral", "femur", "soldra", "perna_tibia", "jarrete_tarso", "metatarso", "boleto_post", "casco_post", "cauda", "d_cranio", "d_cervical", "d_toracica", "d_lombar", "d_sacro_pelve", "d_cauda", "s_pescoco", "s_longuissimo", "s_lombo", "s_gluteos", "s_base_cauda", "vertebra_c1", "vertebra_c2", "vertebra_c3", "vertebra_c4", "vertebra_c5", "vertebra_c6", "vertebra_c7", "vertebra_t1", "vertebra_t2", "vertebra_t3", "vertebra_t4", "vertebra_t5", "vertebra_t6", "vertebra_t7", "vertebra_t8", "vertebra_t9", "vertebra_t10", "vertebra_t11", "vertebra_t12", "vertebra_t13", "vertebra_t14", "vertebra_t15", "vertebra_t16", "vertebra_t17", "vertebra_t18", "vertebra_l1", "vertebra_l2", "vertebra_l3", "vertebra_l4", "vertebra_l5", "vertebra_l6", "vertebra_s1", "vertebra_s2", "vertebra_s3", "vertebra_s4", "vertebra_s5", "vertebra_cd1", "vertebra_cd2", "vertebra_cd3", "vertebra_cd4", "vertebra_cd5"] as const;
export type ParteAnatomicaId = (typeof PARTE_IDS)[number];
export type VistaAnatomica = "dorsal_esqueleto" | "dorsal_superficie" | "lateral";
export type GrupoAnatomico = "osseo" | "articular" | "muscular" | "regiao";
export type TipoParte = "regiao" | "vertebra";
export type Paridade = "axial" | "mediano" | "bilateral";
export type Lateralidade = "direito" | "esquerdo" | "bilateral";
export type SegmentoVertebral = "cervical" | "toracica" | "lombar" | "sacral" | "caudal";
export type Locale = "pt-BR" | "en-US" | "es-ES";

export interface ParteAnatomica {
  readonly id: ParteAnatomicaId; readonly tipo: TipoParte; readonly grupo: GrupoAnatomico;
  readonly paridade: Paridade; readonly segmento?: SegmentoVertebral; readonly ordem?: number;
  readonly vistas: ReadonlyArray<VistaAnatomica>; readonly i18nKey: string;
  readonly nome: Readonly<Record<Locale, string>>;
}

export const PARTES_EQUINAS: Readonly<Record<ParteAnatomicaId, ParteAnatomica>> = {
  cranio: { id: "cranio", tipo: "regiao", grupo: "osseo", paridade: "axial",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.cranio",
    nome: { "pt-BR": "Crânio", "en-US": "Skull", "es-ES": "Cráneo" } },
  mandibula: { id: "mandibula", tipo: "regiao", grupo: "osseo", paridade: "bilateral",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.mandibula",
    nome: { "pt-BR": "Mandíbula", "en-US": "Mandible", "es-ES": "Mandíbula" } },
  regiao_cervical: { id: "regiao_cervical", tipo: "regiao", grupo: "osseo", paridade: "mediano",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.regiao_cervical",
    nome: { "pt-BR": "Região cervical (pescoço)", "en-US": "Cervical region", "es-ES": "Región cervical" } },
  cernelha: { id: "cernelha", tipo: "regiao", grupo: "regiao", paridade: "mediano",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.cernelha",
    nome: { "pt-BR": "Cernelha", "en-US": "Withers", "es-ES": "Cruz" } },
  escapula: { id: "escapula", tipo: "regiao", grupo: "osseo", paridade: "bilateral",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.escapula",
    nome: { "pt-BR": "Escápula", "en-US": "Scapula", "es-ES": "Escápula" } },
  art_ombro: { id: "art_ombro", tipo: "regiao", grupo: "articular", paridade: "bilateral",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.art_ombro",
    nome: { "pt-BR": "Articulação do ombro", "en-US": "Shoulder joint", "es-ES": "Articulación del hombro" } },
  umero: { id: "umero", tipo: "regiao", grupo: "osseo", paridade: "bilateral",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.umero",
    nome: { "pt-BR": "Úmero", "en-US": "Humerus", "es-ES": "Húmero" } },
  cotovelo: { id: "cotovelo", tipo: "regiao", grupo: "articular", paridade: "bilateral",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.cotovelo",
    nome: { "pt-BR": "Cotovelo (codilho)", "en-US": "Elbow", "es-ES": "Codo" } },
  antebraco: { id: "antebraco", tipo: "regiao", grupo: "osseo", paridade: "bilateral",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.antebraco",
    nome: { "pt-BR": "Antebraço (rádio/ulna)", "en-US": "Forearm (radius/ulna)", "es-ES": "Antebrazo" } },
  carpo_ant: { id: "carpo_ant", tipo: "regiao", grupo: "articular", paridade: "bilateral",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.carpo_ant",
    nome: { "pt-BR": "Joelho (carpo) — anterior", "en-US": "Knee (carpus)", "es-ES": "Rodilla (carpo)" } },
  metacarpo: { id: "metacarpo", tipo: "regiao", grupo: "osseo", paridade: "bilateral",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.metacarpo",
    nome: { "pt-BR": "Canela (metacarpo)", "en-US": "Cannon (metacarpus)", "es-ES": "Caña (metacarpo)" } },
  boleto_ant: { id: "boleto_ant", tipo: "regiao", grupo: "articular", paridade: "bilateral",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.boleto_ant",
    nome: { "pt-BR": "Boleto — anterior", "en-US": "Fetlock (front)", "es-ES": "Menudillo anterior" } },
  casco_ant: { id: "casco_ant", tipo: "regiao", grupo: "regiao", paridade: "bilateral",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.casco_ant",
    nome: { "pt-BR": "Casco — anterior", "en-US": "Hoof (front)", "es-ES": "Casco anterior" } },
  dorso: { id: "dorso", tipo: "regiao", grupo: "regiao", paridade: "mediano",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.dorso",
    nome: { "pt-BR": "Dorso (região torácica)", "en-US": "Back (thoracic)", "es-ES": "Dorso (torácico)" } },
  lombo: { id: "lombo", tipo: "regiao", grupo: "regiao", paridade: "mediano",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.lombo",
    nome: { "pt-BR": "Lombo (região lombar)", "en-US": "Loin (lumbar)", "es-ES": "Lomo (lumbar)" } },
  gradil_costal: { id: "gradil_costal", tipo: "regiao", grupo: "osseo", paridade: "bilateral",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.gradil_costal",
    nome: { "pt-BR": "Gradil costal (costelas)", "en-US": "Ribcage", "es-ES": "Parrilla costal" } },
  garupa: { id: "garupa", tipo: "regiao", grupo: "regiao", paridade: "mediano",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.garupa",
    nome: { "pt-BR": "Garupa (sacro/pelve)", "en-US": "Croup (sacrum/pelvis)", "es-ES": "Grupa" } },
  tuber_coxae: { id: "tuber_coxae", tipo: "regiao", grupo: "osseo", paridade: "bilateral",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.tuber_coxae",
    nome: { "pt-BR": "Ponta da anca (tuber coxae)", "en-US": "Point of hip", "es-ES": "Punta del anca" } },
  art_coxofemoral: { id: "art_coxofemoral", tipo: "regiao", grupo: "articular", paridade: "bilateral",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.art_coxofemoral",
    nome: { "pt-BR": "Articulação coxofemoral", "en-US": "Hip joint", "es-ES": "Cadera" } },
  femur: { id: "femur", tipo: "regiao", grupo: "osseo", paridade: "bilateral",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.femur",
    nome: { "pt-BR": "Fêmur", "en-US": "Femur", "es-ES": "Fémur" } },
  soldra: { id: "soldra", tipo: "regiao", grupo: "articular", paridade: "bilateral",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.soldra",
    nome: { "pt-BR": "Soldra (patela/femorotibial)", "en-US": "Stifle", "es-ES": "Babilla" } },
  perna_tibia: { id: "perna_tibia", tipo: "regiao", grupo: "osseo", paridade: "bilateral",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.perna_tibia",
    nome: { "pt-BR": "Perna (tíbia/fíbula)", "en-US": "Gaskin (tibia)", "es-ES": "Pierna (tibia)" } },
  jarrete_tarso: { id: "jarrete_tarso", tipo: "regiao", grupo: "articular", paridade: "bilateral",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.jarrete_tarso",
    nome: { "pt-BR": "Jarrete (tarso/curvilhão)", "en-US": "Hock (tarsus)", "es-ES": "Corvejón (tarso)" } },
  metatarso: { id: "metatarso", tipo: "regiao", grupo: "osseo", paridade: "bilateral",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.metatarso",
    nome: { "pt-BR": "Canela (metatarso)", "en-US": "Cannon (metatarsus)", "es-ES": "Caña (metatarso)" } },
  boleto_post: { id: "boleto_post", tipo: "regiao", grupo: "articular", paridade: "bilateral",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.boleto_post",
    nome: { "pt-BR": "Boleto — posterior", "en-US": "Fetlock (hind)", "es-ES": "Menudillo posterior" } },
  casco_post: { id: "casco_post", tipo: "regiao", grupo: "regiao", paridade: "bilateral",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.casco_post",
    nome: { "pt-BR": "Casco — posterior", "en-US": "Hoof (hind)", "es-ES": "Casco posterior" } },
  cauda: { id: "cauda", tipo: "regiao", grupo: "regiao", paridade: "mediano",
    vistas: ["lateral"], i18nKey: "anatomia.regiao.cauda",
    nome: { "pt-BR": "Cauda (vértebras caudais)", "en-US": "Tail", "es-ES": "Cola" } },
  d_cranio: { id: "d_cranio", tipo: "regiao", grupo: "osseo", paridade: "mediano",
    vistas: ["dorsal_esqueleto"], i18nKey: "anatomia.regiao.d_cranio",
    nome: { "pt-BR": "Crânio (dorsal)", "en-US": "Skull (dorsal)", "es-ES": "Cráneo (dorsal)" } },
  d_cervical: { id: "d_cervical", tipo: "regiao", grupo: "osseo", paridade: "mediano",
    vistas: ["dorsal_esqueleto"], i18nKey: "anatomia.regiao.d_cervical",
    nome: { "pt-BR": "Coluna cervical", "en-US": "Cervical spine", "es-ES": "Columna cervical" } },
  d_toracica: { id: "d_toracica", tipo: "regiao", grupo: "osseo", paridade: "mediano",
    vistas: ["dorsal_esqueleto"], i18nKey: "anatomia.regiao.d_toracica",
    nome: { "pt-BR": "Coluna torácica / costelas", "en-US": "Thoracic spine / ribs", "es-ES": "Columna torácica" } },
  d_lombar: { id: "d_lombar", tipo: "regiao", grupo: "osseo", paridade: "mediano",
    vistas: ["dorsal_esqueleto"], i18nKey: "anatomia.regiao.d_lombar",
    nome: { "pt-BR": "Coluna lombar", "en-US": "Lumbar spine", "es-ES": "Columna lumbar" } },
  d_sacro_pelve: { id: "d_sacro_pelve", tipo: "regiao", grupo: "osseo", paridade: "mediano",
    vistas: ["dorsal_esqueleto"], i18nKey: "anatomia.regiao.d_sacro_pelve",
    nome: { "pt-BR": "Sacro / pelve", "en-US": "Sacrum / pelvis", "es-ES": "Sacro / pelvis" } },
  d_cauda: { id: "d_cauda", tipo: "regiao", grupo: "osseo", paridade: "mediano",
    vistas: ["dorsal_esqueleto"], i18nKey: "anatomia.regiao.d_cauda",
    nome: { "pt-BR": "Cauda", "en-US": "Tail", "es-ES": "Cola" } },
  s_pescoco: { id: "s_pescoco", tipo: "regiao", grupo: "muscular", paridade: "mediano",
    vistas: ["dorsal_superficie"], i18nKey: "anatomia.regiao.s_pescoco",
    nome: { "pt-BR": "Musculatura do pescoço", "en-US": "Neck muscles", "es-ES": "Musculatura del cuello" } },
  s_longuissimo: { id: "s_longuissimo", tipo: "regiao", grupo: "muscular", paridade: "mediano",
    vistas: ["dorsal_superficie"], i18nKey: "anatomia.regiao.s_longuissimo",
    nome: { "pt-BR": "Longuíssimo do dorso", "en-US": "Longissimus dorsi", "es-ES": "Longísimo del dorso" } },
  s_lombo: { id: "s_lombo", tipo: "regiao", grupo: "muscular", paridade: "mediano",
    vistas: ["dorsal_superficie"], i18nKey: "anatomia.regiao.s_lombo",
    nome: { "pt-BR": "Musculatura lombar", "en-US": "Lumbar muscles", "es-ES": "Musculatura lumbar" } },
  s_gluteos: { id: "s_gluteos", tipo: "regiao", grupo: "muscular", paridade: "mediano",
    vistas: ["dorsal_superficie"], i18nKey: "anatomia.regiao.s_gluteos",
    nome: { "pt-BR": "Glúteos / garupa", "en-US": "Gluteal muscles", "es-ES": "Glúteos" } },
  s_base_cauda: { id: "s_base_cauda", tipo: "regiao", grupo: "muscular", paridade: "mediano",
    vistas: ["dorsal_superficie"], i18nKey: "anatomia.regiao.s_base_cauda",
    nome: { "pt-BR": "Base da cauda", "en-US": "Tail base", "es-ES": "Base de la cola" } },
  vertebra_c1: { id: "vertebra_c1", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "cervical", ordem: 1,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.c1",
    nome: { "pt-BR": "Atlas (C1)", "en-US": "Atlas (C1)", "es-ES": "Atlas (C1)" } },
  vertebra_c2: { id: "vertebra_c2", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "cervical", ordem: 2,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.c2",
    nome: { "pt-BR": "Áxis (C2)", "en-US": "Axis (C2)", "es-ES": "Axis (C2)" } },
  vertebra_c3: { id: "vertebra_c3", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "cervical", ordem: 3,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.c3",
    nome: { "pt-BR": "Vértebra cervical C3", "en-US": "Cervical vertebra C3", "es-ES": "Vértebra cervical C3" } },
  vertebra_c4: { id: "vertebra_c4", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "cervical", ordem: 4,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.c4",
    nome: { "pt-BR": "Vértebra cervical C4", "en-US": "Cervical vertebra C4", "es-ES": "Vértebra cervical C4" } },
  vertebra_c5: { id: "vertebra_c5", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "cervical", ordem: 5,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.c5",
    nome: { "pt-BR": "Vértebra cervical C5", "en-US": "Cervical vertebra C5", "es-ES": "Vértebra cervical C5" } },
  vertebra_c6: { id: "vertebra_c6", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "cervical", ordem: 6,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.c6",
    nome: { "pt-BR": "Vértebra cervical C6", "en-US": "Cervical vertebra C6", "es-ES": "Vértebra cervical C6" } },
  vertebra_c7: { id: "vertebra_c7", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "cervical", ordem: 7,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.c7",
    nome: { "pt-BR": "Vértebra cervical C7", "en-US": "Cervical vertebra C7", "es-ES": "Vértebra cervical C7" } },
  vertebra_t1: { id: "vertebra_t1", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "toracica", ordem: 1,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.t1",
    nome: { "pt-BR": "Vértebra torácica T1", "en-US": "Thoracic vertebra T1", "es-ES": "Vértebra torácica T1" } },
  vertebra_t2: { id: "vertebra_t2", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "toracica", ordem: 2,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.t2",
    nome: { "pt-BR": "Vértebra torácica T2", "en-US": "Thoracic vertebra T2", "es-ES": "Vértebra torácica T2" } },
  vertebra_t3: { id: "vertebra_t3", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "toracica", ordem: 3,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.t3",
    nome: { "pt-BR": "Vértebra torácica T3", "en-US": "Thoracic vertebra T3", "es-ES": "Vértebra torácica T3" } },
  vertebra_t4: { id: "vertebra_t4", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "toracica", ordem: 4,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.t4",
    nome: { "pt-BR": "Vértebra torácica T4", "en-US": "Thoracic vertebra T4", "es-ES": "Vértebra torácica T4" } },
  vertebra_t5: { id: "vertebra_t5", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "toracica", ordem: 5,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.t5",
    nome: { "pt-BR": "Vértebra torácica T5", "en-US": "Thoracic vertebra T5", "es-ES": "Vértebra torácica T5" } },
  vertebra_t6: { id: "vertebra_t6", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "toracica", ordem: 6,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.t6",
    nome: { "pt-BR": "Vértebra torácica T6", "en-US": "Thoracic vertebra T6", "es-ES": "Vértebra torácica T6" } },
  vertebra_t7: { id: "vertebra_t7", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "toracica", ordem: 7,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.t7",
    nome: { "pt-BR": "Vértebra torácica T7", "en-US": "Thoracic vertebra T7", "es-ES": "Vértebra torácica T7" } },
  vertebra_t8: { id: "vertebra_t8", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "toracica", ordem: 8,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.t8",
    nome: { "pt-BR": "Vértebra torácica T8", "en-US": "Thoracic vertebra T8", "es-ES": "Vértebra torácica T8" } },
  vertebra_t9: { id: "vertebra_t9", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "toracica", ordem: 9,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.t9",
    nome: { "pt-BR": "Vértebra torácica T9", "en-US": "Thoracic vertebra T9", "es-ES": "Vértebra torácica T9" } },
  vertebra_t10: { id: "vertebra_t10", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "toracica", ordem: 10,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.t10",
    nome: { "pt-BR": "Vértebra torácica T10", "en-US": "Thoracic vertebra T10", "es-ES": "Vértebra torácica T10" } },
  vertebra_t11: { id: "vertebra_t11", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "toracica", ordem: 11,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.t11",
    nome: { "pt-BR": "Vértebra torácica T11", "en-US": "Thoracic vertebra T11", "es-ES": "Vértebra torácica T11" } },
  vertebra_t12: { id: "vertebra_t12", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "toracica", ordem: 12,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.t12",
    nome: { "pt-BR": "Vértebra torácica T12", "en-US": "Thoracic vertebra T12", "es-ES": "Vértebra torácica T12" } },
  vertebra_t13: { id: "vertebra_t13", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "toracica", ordem: 13,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.t13",
    nome: { "pt-BR": "Vértebra torácica T13", "en-US": "Thoracic vertebra T13", "es-ES": "Vértebra torácica T13" } },
  vertebra_t14: { id: "vertebra_t14", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "toracica", ordem: 14,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.t14",
    nome: { "pt-BR": "Vértebra torácica T14", "en-US": "Thoracic vertebra T14", "es-ES": "Vértebra torácica T14" } },
  vertebra_t15: { id: "vertebra_t15", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "toracica", ordem: 15,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.t15",
    nome: { "pt-BR": "Vértebra torácica T15", "en-US": "Thoracic vertebra T15", "es-ES": "Vértebra torácica T15" } },
  vertebra_t16: { id: "vertebra_t16", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "toracica", ordem: 16,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.t16",
    nome: { "pt-BR": "Vértebra torácica T16", "en-US": "Thoracic vertebra T16", "es-ES": "Vértebra torácica T16" } },
  vertebra_t17: { id: "vertebra_t17", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "toracica", ordem: 17,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.t17",
    nome: { "pt-BR": "Vértebra torácica T17", "en-US": "Thoracic vertebra T17", "es-ES": "Vértebra torácica T17" } },
  vertebra_t18: { id: "vertebra_t18", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "toracica", ordem: 18,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.t18",
    nome: { "pt-BR": "Vértebra torácica T18", "en-US": "Thoracic vertebra T18", "es-ES": "Vértebra torácica T18" } },
  vertebra_l1: { id: "vertebra_l1", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "lombar", ordem: 1,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.l1",
    nome: { "pt-BR": "Vértebra lombar L1", "en-US": "Lumbar vertebra L1", "es-ES": "Vértebra lombar L1" } },
  vertebra_l2: { id: "vertebra_l2", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "lombar", ordem: 2,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.l2",
    nome: { "pt-BR": "Vértebra lombar L2", "en-US": "Lumbar vertebra L2", "es-ES": "Vértebra lombar L2" } },
  vertebra_l3: { id: "vertebra_l3", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "lombar", ordem: 3,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.l3",
    nome: { "pt-BR": "Vértebra lombar L3", "en-US": "Lumbar vertebra L3", "es-ES": "Vértebra lombar L3" } },
  vertebra_l4: { id: "vertebra_l4", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "lombar", ordem: 4,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.l4",
    nome: { "pt-BR": "Vértebra lombar L4", "en-US": "Lumbar vertebra L4", "es-ES": "Vértebra lombar L4" } },
  vertebra_l5: { id: "vertebra_l5", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "lombar", ordem: 5,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.l5",
    nome: { "pt-BR": "Vértebra lombar L5", "en-US": "Lumbar vertebra L5", "es-ES": "Vértebra lombar L5" } },
  vertebra_l6: { id: "vertebra_l6", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "lombar", ordem: 6,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.l6",
    nome: { "pt-BR": "Vértebra lombar L6", "en-US": "Lumbar vertebra L6", "es-ES": "Vértebra lombar L6" } },
  vertebra_s1: { id: "vertebra_s1", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "sacral", ordem: 1,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.s1",
    nome: { "pt-BR": "Vértebra sacral S1", "en-US": "Sacral vertebra S1", "es-ES": "Vértebra sacral S1" } },
  vertebra_s2: { id: "vertebra_s2", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "sacral", ordem: 2,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.s2",
    nome: { "pt-BR": "Vértebra sacral S2", "en-US": "Sacral vertebra S2", "es-ES": "Vértebra sacral S2" } },
  vertebra_s3: { id: "vertebra_s3", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "sacral", ordem: 3,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.s3",
    nome: { "pt-BR": "Vértebra sacral S3", "en-US": "Sacral vertebra S3", "es-ES": "Vértebra sacral S3" } },
  vertebra_s4: { id: "vertebra_s4", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "sacral", ordem: 4,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.s4",
    nome: { "pt-BR": "Vértebra sacral S4", "en-US": "Sacral vertebra S4", "es-ES": "Vértebra sacral S4" } },
  vertebra_s5: { id: "vertebra_s5", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "sacral", ordem: 5,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.s5",
    nome: { "pt-BR": "Vértebra sacral S5", "en-US": "Sacral vertebra S5", "es-ES": "Vértebra sacral S5" } },
  vertebra_cd1: { id: "vertebra_cd1", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "caudal", ordem: 1,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.cd1",
    nome: { "pt-BR": "Vértebra caudal Cd1", "en-US": "Caudal vertebra Cd1", "es-ES": "Vértebra caudal Cd1" } },
  vertebra_cd2: { id: "vertebra_cd2", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "caudal", ordem: 2,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.cd2",
    nome: { "pt-BR": "Vértebra caudal Cd2", "en-US": "Caudal vertebra Cd2", "es-ES": "Vértebra caudal Cd2" } },
  vertebra_cd3: { id: "vertebra_cd3", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "caudal", ordem: 3,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.cd3",
    nome: { "pt-BR": "Vértebra caudal Cd3", "en-US": "Caudal vertebra Cd3", "es-ES": "Vértebra caudal Cd3" } },
  vertebra_cd4: { id: "vertebra_cd4", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "caudal", ordem: 4,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.cd4",
    nome: { "pt-BR": "Vértebra caudal Cd4", "en-US": "Caudal vertebra Cd4", "es-ES": "Vértebra caudal Cd4" } },
  vertebra_cd5: { id: "vertebra_cd5", tipo: "vertebra", grupo: "osseo", paridade: "mediano", segmento: "caudal", ordem: 5,
    vistas: ["lateral", "dorsal_esqueleto"], i18nKey: "anatomia.vertebra.cd5",
    nome: { "pt-BR": "Vértebra caudal Cd5", "en-US": "Caudal vertebra Cd5", "es-ES": "Vértebra caudal Cd5" } },
} as const;

export const parteAnatomicaIdSchema = z.enum(PARTE_IDS);
export const lateralidadeSchema = z.enum(["direito", "esquerdo", "bilateral"]);

export const listarVertebras = (seg?: SegmentoVertebral): ParteAnatomica[] =>
  Object.values(PARTES_EQUINAS).filter((p) => p.tipo === "vertebra" && (!seg || p.segmento === seg));
